# Generated by Django 5.1.3 on 2025-01-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chores_manager", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="chore",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
