# Generated by Django 5.1.3 on 2025-01-23 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chores_manager", "0004_chore_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userchoresummary",
            name="completed_chore_events",
        ),
        migrations.AddField(
            model_name="chore",
            name="user_summary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chores",
                to="chores_manager.userchoresummary",
            ),
        ),
        migrations.AlterField(
            model_name="userchoresummary",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
