# Generated by Django 5.1.3 on 2025-01-23 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "chores_manager",
            "0005_remove_userchoresummary_completed_chore_events_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chore",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="chore",
            name="meal_time",
            field=models.CharField(
                choices=[
                    ("Breakfast", "Breakfast"),
                    ("Lunch", "Lunch"),
                    ("Dinner", "Dinner"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="chore",
            name="user_summary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chores_manager.userchoresummary",
            ),
        ),
        migrations.AlterField(
            model_name="userchoresummary",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chore_summary",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
