# Generated by Django 5.1.1 on 2024-10-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("totalfootball", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="starting_lineup",
            field=models.ManyToManyField(
                blank=True, related_name="starting_lineups", to="totalfootball.player"
            ),
        ),
    ]
