# Generated by Django 5.1.3 on 2024-11-17 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalfootball', '0002_team_starting_lineup'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='player',
            name='api_football_id',
            field=models.IntegerField(blank=True, help_text='ID from API-Football', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='league_api_id',
            field=models.IntegerField(blank=True, help_text='League ID from API-Football', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='team_api_id',
            field=models.IntegerField(blank=True, help_text='Team ID from API-Football', null=True),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('user', 'league'), name='unique_user_league'),
        ),
        migrations.AddField(
            model_name='leagueteam',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='league_team_captain', to='totalfootball.player'),
        ),
        migrations.AddField(
            model_name='leagueteam',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_teams', to='totalfootball.league'),
        ),
        migrations.AddField(
            model_name='leagueteam',
            name='players',
            field=models.ManyToManyField(related_name='league_teams', to='totalfootball.player'),
        ),
        migrations.AddField(
            model_name='leagueteam',
            name='starting_lineup',
            field=models.ManyToManyField(blank=True, related_name='league_team_starting_lineup', to='totalfootball.player'),
        ),
        migrations.AddField(
            model_name='leagueteam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
