# Generated by Django 5.1.3 on 2024-11-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalfootball', '0003_leagueteam_alter_team_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='past_points',
            field=models.IntegerField(default=0),
        ),
    ]
