# Generated by Django 4.2.16 on 2024-11-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalfootball', '0004_player_past_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='current_pick',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='league',
            name='draft_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='league',
            name='total_picks',
            field=models.IntegerField(default=15),
        ),
    ]
