# Generated by Django 4.2.16 on 2024-11-19 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('totalfootball', '0006_player_assists_player_duels_player_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='direction',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_number', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='totalfootball.league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='totalfootball.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='totalfootball.team')),
            ],
        ),
    ]
