# Generated by Django 4.2.16 on 2024-11-19 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('totalfootball', '0007_league_direction_draftpick'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='draftpick',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='totalfootball.league'),
        ),
        migrations.AlterField(
            model_name='draftpick',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='totalfootball.player'),
        ),
        migrations.AlterField(
            model_name='draftpick',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='totalfootball.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='api_football_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='league_api_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team_api_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='draftpick',
            constraint=models.UniqueConstraint(fields=('league', 'player'), name='unique_draft_pick_per_league'),
        ),
    ]
