# Generated by Django 4.2.16 on 2024-11-19 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('totalfootball', '0008_league_round_number_player_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpick',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='totalfootball.leagueteam'),
        ),
    ]
