# Generated by Django 4.2.16 on 2024-11-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalfootball', '0009_alter_draftpick_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='new_assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='new_duels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='new_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='new_saves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='new_tackles',
            field=models.IntegerField(default=0),
        ),
    ]
