# Generated by Django 5.1.1 on 2024-11-21 22:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("totalfootball", "0011_alter_player_last_updated"),
    ]

    operations = [
        #migrations.RemoveField(
        #   model_name="team",
        #   name="league",
        #),
    ]
