# Generated by Django 5.1.1 on 2024-11-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("totalfootball", "0012_remove_team_league"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="team",
            name="unique_user_league",
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_user_team"
            ),
        ),
    ]
