# Generated by Django 5.1.1 on 2024-11-21 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("totalfootball", "0013_remove_team_unique_user_league_team_unique_user_team"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="team",
            name="unique_user_team",
        ),
        migrations.AlterField(
            model_name="team",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
