# Generated by Django 5.1.1 on 2024-11-21 22:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("totalfootball", "0014_remove_team_unique_user_team_alter_team_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="league",
        ),
    ]
