# Generated by Django 5.1.1 on 2024-11-22 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("totalfootball", "0015_remove_team_league"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="draft_room_members",
            field=models.ManyToManyField(
                blank=True, related_name="draft_rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
