# Generated by Django 5.1.1 on 2024-11-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("totalfootball", "0016_league_draft_room_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="draft_direction",
            field=models.BooleanField(default=True),
        ),
    ]
