# Generated by Django 5.1.1 on 2024-11-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("totalfootball", "0017_league_draft_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="draft_round",
            field=models.IntegerField(default=1),
        ),
    ]
